name: services/website

on:
  pull_request:
    paths:
      - "services/website/**"

jobs:
  test_setup:
    name: Test setup
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
    steps:
      - name: Wait for Vercel preview deployment to be ready
        uses: patrickedqvist/wait-for-vercel-preview@master
        id: waitForVercelPreviewDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 60
  test_lighthouse:
    name: Test Lighthouse
    needs: test_setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit Vercel preview URL using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            ${{ needs.test_setup.outputs.preview_url }}
          budgetPath: ./services/website/.config/lighthouse/budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
  test_e2e:
    name: Test end-to-end
    needs: test_setup
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache services/website/node_modules and Cypress
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            services/website/node_modules
          key: services-website-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install Cypress
        working-directory: services/website
        run: npm i cypress
      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          config: baseUrl=${{ needs.test_setup.outputs.preview_url }}
          install: false # We test a live preview URL, no need to install packages
          working-directory: services/website
  test_a11y:
    name: Test a11y
    needs: test_setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test a11y
        working-directory: services/website
        run: |
          npx pa11y-ci --config .config/pa11yci.json --sitemap ${{ needs.test_setup.outputs.preview_url }}/sitemap.xml --sitemap-find https://www.mikenikles.com --sitemap-replace ${{ needs.test_setup.outputs.preview_url }}
